name: Build and Release .NET Installer

on:
  # Run on pushes to your main development branch (e.g., master, main, devel)
  push:
    branches: [ master ]
  # Run on pull requests targeting your main development branch
  pull_request:
    branches: [ master ]
  # Run when a release is created in the GitHub UI
  release:
    types: [created]

jobs:
  build:
    name: Build MSI Installer
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSBuild
        # This action finds the pre-installed MSBuild and adds it to the PATH
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      # CORRECT WAY TO SETUP WIX: Use the official action.
      # This is faster and more reliable than manual download/cache/path steps.
      - name: Setup WiX v3 Toolset
        uses: wixtoolset/wix-v3-action@v1
        with:
          # You can specify the exact version you need
          version: v3.14.0

      # The failing ".NET Framework 4.8 Developer Pack" step has been REMOVED.
      # It is already included in the 'windows-latest' runner environment.

      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          # This key is more robust and will invalidate the cache if any project file changes.
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj', '**/*.sln') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore NuGet packages
        run: nuget restore TinyWall.sln

      - name: Build TinyWall Application
        # Building the entire solution ensures all project dependencies are built.
        run: msbuild TinyWall.sln /p:Configuration=Release /p:Platform="Any CPU"

      - name: Prepare files for installer
        shell: pwsh
        run: |
          $ErrorActionPreference = "Stop"

          # 1. Verify that the main application was built successfully
          $appExe = "TinyWall\bin\Release\TinyWall.exe"
          if (-Not (Test-Path $appExe)) {
            Write-Error "ERROR: $appExe not found after build. Check the build log for errors."
            exit 1
          }
          Write-Host "✓ Application executable found."

          # 2. Create the target directory for the installer files
          $targetDir = "MsiSetup\Sources\ProgramFiles\TinyWall"
          New-Item -ItemType Directory -Force -Path $targetDir

          # 3. Copy the built application files into the installer source folder
          $sourceDir = "TinyWall\bin\Release"
          Copy-Item -Path "$sourceDir\*" -Destination $targetDir -Recurse -Force
          Write-Host "✓ Copied application files from $sourceDir to $targetDir"

          # 4. Copy the database and other common data files
          $dbSourceDir = "TinyWall\Database"
          $dbTargetDir = "MsiSetup\Sources\CommonAppData\TinyWall"
          if (Test-Path $dbSourceDir) {
            if (-Not (Test-Path $dbTargetDir)) {
              New-Item -ItemType Directory -Path $dbTargetDir -Force
            }
            Copy-Item -Path "$dbSourceDir\*" -Destination $dbTargetDir -Recurse -Force
            Write-Host "✓ Copied database files to $dbTargetDir"
          }

      - name: Build MSI Installer
        run: msbuild MsiSetup\MsiSetup.wixproj /p:Configuration=Release /p:Platform=x86

      - name: Verify MSI output
        shell: pwsh
        run: |
          $msiFile = "MsiSetup\bin\Release\TinyWallInstaller.msi"
          if (-Not (Test-Path $msiFile)) {
            Write-Error "ERROR: Installer file $msiFile not found after WiX build."
            exit 1
          }
          $msiInfo = Get-Item $msiFile
          Write-Host "✓ MSI installer created successfully: $($msiInfo.Name) ($([math]::Round($msiInfo.Length / 1MB, 2)) MB)"

      - name: Upload MSI as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: TinyWall-Installer
          path: MsiSetup/bin/Release/TinyWallInstaller.msi

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest # Can be ubuntu-latest, as it's just downloading/uploading
    if: github.event_name == 'release'

    steps:
      - name: Download MSI from build job
        uses: actions/download-artifact@v4
        with:
          name: TinyWall-Installer
          
      - name: Create Release and Upload MSI
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.release.tag_name }}
          name: Release ${{ github.event.release.name }}
          body: ${{ github.event.release.body }}
          prerelease: ${{ github.event.release.prerelease }}
          files: TinyWallInstaller.msi
